includes:
    - "../../ci_base.yml"
    - "../benchmarks.yml"

runtimes:
    jdk-mmtk:
        type: OpenJDK
        release: 11
        home: "./build/jdk-stock/jdk"

configs:
    - "jdk-mmtk|ms|s|c2|epsilon|heap120g"
    - "jdk-mmtk|ms|s|c2|sgc"
    - "jdk-mmtk|ms|s|c2|pgc"
    - "jdk-mmtk|ms|s|c2|g1"
    - "jdk-mmtk|ms|s|c2|zgc"
    - "jdk-mmtk|ms|s|c2|cms"