name: jikesrvm
plans:
  - plan: nogc
    baseline: ['JavaMMTk_NoGC']
  - plan: semispace
    baseline: ['JavaMMTk_SemiSpace']
  - plan: marksweep
    baseline: []
notes:
  - date: "20230116"
    time: "0000"
    note: "Move to Ubuntu 22.04"
  - date: "20231017"
    time: "0000"
    note: "Speculative RAS Overflow mitigation on Zen1/Zen2"
  - date: "20231103"
    time: "0800"
    note: "Move to running-ng"
  - date: "20240403"
    time: "0000"
    note: "Move to Rust 1.77.0"
  - date: "20240802"
    time: "0000"
    note: "Microcode update for Zenbleed"
  - date: "20240903"
    time: "0000"
    note: "Move to Linux Kernel 6.8.0"
