name: jikesrvm
plans:
  - plan: nogc
    baseline: ['JavaMMTk_NoGC']
  - plan: semispace
    baseline: ['JavaMMTk_SemiSpace']
  - plan: marksweep
    baseline: []
notes:
  - date: "20230116"
    note: "Move to Ubuntu 22.04"
  - date: "20231015"
    note: "Speculative RAS Overflow mitigation on Zen1/Zen2"
  - date: "20231102"
    note: "Move to running-ng"
  - date: "20240403"
    note: "Move to Rust 1.77.0"
