name: openjdk
plans:
  - plan: nogc
    baseline: ['jdk-epsilon']
  - plan: semispace
    baseline: ['jdk-g1', 'jdk-zgc']
  - plan: gencopy
    baseline: ['jdk-g1', 'jdk-zgc']
  - plan: immix
    baseline: ['jdk-g1', 'jdk-zgc']
  - plan: genimmix
    baseline: ['jdk-g1', 'jdk-zgc']
  - plan: stickyimmix
    baseline: ['jdk-g1', 'jdk-zgc']
