name: openjdk
plans:
  - plan: nogc
    baseline: ['jdk-epsilon']
  - plan: semispace
    baseline: ['jdk-g1', 'jdk-zgc']
  - plan: gencopy
    baseline: ['jdk-g1', 'jdk-zgc']
  - plan: immix
    baseline: ['jdk-g1', 'jdk-zgc']
  - plan: genimmix
    baseline: ['jdk-g1', 'jdk-zgc']
  - plan: stickyimmix
    baseline: ['jdk-g1', 'jdk-zgc']
  - plan: marksweep
    baseline: ['jdk-g1', 'jdk-zgc']
notes:
  - date: "20230116"
    note: "Move to Ubuntu 22.04"
  - date: "20231015"
    note: "Speculative RAS Overflow mitigation on Zen1/Zen2"
  - date: "20231102"
    note: "Move to running-ng. Use -Xcomp. Use image build."
  - date: "20240403"
    note: "Move to Rust 1.77.0"
  - date: "20240903"
    note: "Move to Linux Kernel 6.8.0"
