name: openjdk
plans:
  - plan: nogc
    baseline: ['jdk-epsilon']
  - plan: semispace
    baseline: ['jdk-g1', 'jdk-zgc']
  - plan: gencopy
    baseline: ['jdk-g1', 'jdk-zgc']
  - plan: immix
    baseline: ['jdk-g1', 'jdk-zgc']
  - plan: genimmix
    baseline: ['jdk-g1', 'jdk-zgc']
  - plan: stickyimmix
    baseline: ['jdk-g1', 'jdk-zgc']
  - plan: marksweep
    baseline: ['jdk-g1', 'jdk-zgc']
  # "canary" is not a real plan.  It is for the canary build.
  # We add it here to make history_report.py recognize its result
  # and plot it in a separate block in parallel to other real plans in OpenJDK.
  - plan: canary
    baseline: ['jdk-g1', 'jdk-zgc']
notes:
  - date: "20230116"
    time: "0000"
    note: "Move to Ubuntu 22.04"
  - date: "20231017"
    time: "0000"
    note: "Speculative RAS Overflow mitigation on Zen1/Zen2"
  - date: "20231103"
    time: "0800"
    note: "Move to running-ng. Use -Xcomp. Use image build."
  - date: "20240403"
    time: "0000"
    note: "Move to Rust 1.77.0"
  - date: "20240802"
    time: "0000"
    note: "Microcode update for Zenbleed"
  - date: "20240903"
    time: "0000"
    note: "Move to Linux Kernel 6.8.0"
