includes:
  - "./running-base.yml"

benchmarks:
  dacapo2006:
    - antlr
    - bloat
    - eclipse
    - fop
    - xalan
    - jython
    - luindex
    - lusearch
    - pmd
    - sunflow
    - hsqldb

modifiers:
  ig:
    type: JVMArg
    val: "-X:gc:ignoreSystemGC=true"

overrides:
  "suites.dacapo2006.minheap_values.from_old_running_scripts":
    antlr: 24
    bloat: 33
    eclipse: 84
    fop: 40
    xalan: 54
    jython: 40
    luindex: 22
    lusearch: 34
    pmd: 49
    sunflow: 54
    hsqldb: 127
  "suites.dacapo2006.minheap": "from_old_running_scripts"
