includes:
  - "./running-jikesrvm-base.yml"

# Specific to NoGC (only a few benchmarks can run with limited heap size 4G max, run fewer interations)
overrides:
    "suites.dacapo2006.timing_iteration": 2
    "benchmarks.dacapo2006":
        - antlr
        - fop
        - luindex

runtimes:
  NoGC:
    type: JikesRVM
    home: "./build/NoGC_x86_64_m32-linux"

configs:
  - "NoGC|heap4g"
