includes:
  - "$RUNNING_NG_PACKAGE_DATA/base/runbms.yml"

overrides:
  "remote_host": null
  "suites.dacapo2006.timing_iteration": 2

modifiers:
    # Fixed large heap sizes - for NoGC
    heap8g:
      type: JVMArg
      val: "-Xms8000M -Xmx8000M"
    heap4g:
      type: JVMArg
      val: "-Xms4000M -Xmx4000M"

    # Probes
    probes_cp:
      type: JVMClasspath
      val: "$PWD/probes/rust_mmtk/java $PWD/probes/openjdk/java $PWD/probes/probes.jar"
    probes_rustmmtk:
      type: JVMArg
      val: "-Dprobes=RustMMTk -Djava.library.path=$PWD/probes/rust_mmtk"
    probes_openjdk:
      type: JVMArg
      val: "-Dprobes=OpenJDK"

    # Select GC algorithm
    ## Rust MMTk
    mmtk_gc:
      type: EnvVar
      var: "MMTK_PLAN"
      val: "{0}"
    semispace:
      type: EnvVar
      var: "MMTK_PLAN"
      val: "SemiSpace"
    immix:
      type: EnvVar
      var: "MMTK_PLAN"
      val: "Immix"
    gencopy:
      type: EnvVar
      var: "MMTK_PLAN"
      val: "GenCopy"
    genimmix:
      type: EnvVar
      var: "MMTK_PLAN"
      val: "GenImmix"
    marksweep:
      type: EnvVar
      var: "MMTK_PLAN"
      val: "MarkSweep"
    nogc:
      type: EnvVar
      var: "MMTK_PLAN"
      val: "NoGC"
    stickyimmix:
      type: EnvVar
      var: "MMTK_PLAN"
      val: "StickyImmix"
