includes:
  - "./running-jikesrvm-base.yml"

# Specific to NoGC (run fewer iterations)
overrides:
    "suites.dacapo2006.timing_iteration": 2

runtimes:
  JavaMMTk_NoGC:
    type: JikesRVM
    home: "./build/JavaMMTk_NoGC_x86_64_m32-linux"

configs:
  - "JavaMMTk_NoGC|ig|heap4g"
