includes:
  - "./running-jikesrvm-base.yml"

# Specific to NoGC (run fewer iterations)
overrides:
    "suites.dacapo2006.timing_iteration": 2

runtimes:
  NoGC:
    type: JikesRVM
    home: "./build/NoGC_x86_64_m32-linux"

configs:
  - "NoGC|heap4g"
