includes:
  - "./running-jikesrvm-base.yml"

runtimes:
  MarkSweep_Trunk:
    type: JikesRVM
    home: "./build/MarkSweep_Trunk_x86_64_m32-linux"
  MarkSweep_Branch:
    type: JikesRVM
    home: "./build/MarkSweep_Branch_x86_64_m32-linux"

configs:
  - "MarkSweep_Trunk"
  - "MarkSweep_Branch"
