import os
import parse

# The runtime configs that define what a complete index.html should list,
# when a caller doesn't say otherwise (see generate_index's config_filenames
# param). Every history_report.py invocation regenerates the index from
# *all* configs it's given, regardless of which single config/plan it was
# actually asked to render - so a per-commit run that only touches one plan
# still writes a complete, correct index.html into its output_dir alongside
# that plan's page. The external deploy step (outside this repo) syncs
# output_dir into the destination folder with existing files kept, so
# whichever runtime's report ran most recently "wins" and leaves the same
# complete index behind either way.
DEFAULT_CONFIG_FILENAMES = ["openjdk-plot.yml", "jikesrvm-plot.yml"]


# A plan can independently opt into `time: true` and/or `latency: true` (see
# openjdk-plot.yml) - each enabled metric gets its own card, so a plan with
# both gets two: "<runtime>-<plan>-time" and "<runtime>-<plan>-latency",
# linking to "<runtime>_<plan>_<metric>_history.{html,png}" (see
# history_report.py, which writes exactly those names for each metric it
# renders).
CARD_METRICS = ["time", "latency"]


def _collect_cards(config_dir, config_filenames):
    cards = []
    for filename in config_filenames:
        path = os.path.join(config_dir, filename)
        if not os.path.isfile(path):
            continue
        config = parse.parse_yaml(path)
        runtime = config["name"]
        for p in config["plans"]:
            if p.get("hidden", False):
                continue
            for metric in CARD_METRICS:
                if p.get(metric, False):
                    cards.append({"runtime": runtime, "plan": p["plan"], "metric": metric})
    return cards


def _render_html(cards):
    import json
    cards_json = json.dumps(cards, indent=2)

    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>MMTk Performance Regression</title>
<!--
  Generated by ci-perf-kit/scripts/index_gen.py (called from history_report.py)
  every time a report is rendered - do not hand-edit, it will be overwritten.

  Each card is a static sparkline PNG (see plot.py's `sparkline` mode), one
  per plan per enabled metric (suffixed "-time" or "-latency" - see
  CARD_METRICS above):
  - "-time" cards: one row per benchmark, total time (colored green/red/muted
    for improvement/regression/neutral, with the current value as the big
    number) plus mutator/STW time as thin informational overlay lines.
  - "-latency" cards: one row per benchmark with latency data, the
    50/90/99/99.9/99.99th percentile tail latency (metered, corrected for
    coordinated omission - see parse.py) on a log scale.
  Click a card to open the full interactive page for that plan/metric.
-->
<style>
  :root {
    color-scheme: light;
    --surface-page:   #f9f9f7;
    --surface-card:   #fcfcfb;
    --ink-primary:    #0b0b0b;
    --ink-secondary:  #52514e;
    --ink-muted:      #898781;
    --border:         rgba(11, 11, 11, 0.10);
  }
  @media (prefers-color-scheme: dark) {
    :root:where(:not([data-theme="light"])) {
      color-scheme: dark;
      --surface-page:   #0d0d0d;
      --surface-card:   #1a1a19;
      --ink-primary:    #ffffff;
      --ink-secondary:  #c3c2b7;
      --ink-muted:      #898781;
      --border:         rgba(255, 255, 255, 0.10);
    }
  }
  :root[data-theme="dark"] {
    color-scheme: dark;
    --surface-page:   #0d0d0d;
    --surface-card:   #1a1a19;
    --ink-primary:    #ffffff;
    --ink-secondary:  #c3c2b7;
    --ink-muted:      #898781;
    --border:         rgba(255, 255, 255, 0.10);
  }

  * { box-sizing: border-box; }

  body {
    margin: 0;
    padding: 24px;
    background: var(--surface-page);
    color: var(--ink-primary);
    font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
  }

  h1 {
    font-size: 20px;
    margin: 0 0 4px;
  }
  p.subtitle {
    margin: 0 0 24px;
    color: var(--ink-secondary);
    font-size: 13px;
  }

  .plan-grid {
    display: flex;
    flex-wrap: wrap;
    gap: 14px;
  }

  .plan-card {
    display: block;
    width: 300px;
    border: 1px solid var(--border);
    border-radius: 8px;
    background: var(--surface-card);
    overflow: hidden;
    text-decoration: none;
    color: inherit;
    transition: border-color 0.15s ease, transform 0.15s ease;
  }
  .plan-card:hover {
    border-color: var(--ink-secondary);
    transform: translateY(-1px);
  }
  .plan-card .plan-name {
    padding: 8px 12px;
    font-size: 13px;
    font-weight: 600;
    border-bottom: 1px solid var(--border);
  }
  .plan-card img {
    display: block;
    width: 100%%;
    height: auto;
  }
  .plan-card.missing {
    display: none;
  }
</style>
</head>
<body>

<h1>MMTk Performance Regression</h1>
<p class="subtitle">Each card is one plan's history for one metric (see the -time / -latency suffix). Time cards: total time per benchmark (big number/line colored green improvement, red regression, gray neutral), with mutator/STW time as thin informational overlays. Latency cards: 50/90/99/99.9/99.99th percentile tail latency per benchmark, log scale. Click a card for the full interactive history.</p>

<div class="plan-grid" id="plan-grid"></div>

<script>
  // Pages/images referenced below live in this same folder - no path prefix.
  // Generated from configs/*-plot.yml by index_gen.py; do not hand-edit.
  const cards = %s;

  const grid = document.getElementById("plan-grid");

  for (const { runtime, plan, metric } of cards) {
    const prefix = `${runtime}_${plan}_${metric}`;
    const title = `${runtime}-${plan}-${metric}`;

    const card = document.createElement("a");
    card.className = "plan-card";
    card.href = `${prefix}_history.html`;
    card.target = "_blank";
    card.rel = "noopener";

    const name = document.createElement("div");
    name.className = "plan-name";
    name.textContent = title;
    card.appendChild(name);

    const img = document.createElement("img");
    img.src = `${prefix}_history.png`;
    img.loading = "lazy";
    img.alt = `${title} performance history`;
    // A plan with no report yet (e.g. newly added, or not touched by this
    // particular run) shouldn't leave a broken-image icon in the dashboard -
    // just hide the whole card.
    img.onerror = () => card.classList.add("missing");
    card.appendChild(img);

    grid.appendChild(card);
  }
</script>

</body>
</html>
""" % cards_json


# output_dir: where history_report.py just wrote this run's *_time_history.{html,png}
# and *_latency_history.{html,png} files - the generated index.html is written
# alongside them, referencing them (and every other plan/metric from
# config_filenames) with plain relative filenames.
# config_filenames: which configs/*.yml files to list cards from. Defaults to
# DEFAULT_CONFIG_FILENAMES - the two configs every routine per-commit/weekly
# workflow uses. A caller rendering against a non-default config (e.g.
# render_all.py, when a manual run points at a differently-named plot config)
# must pass the actual filenames it used, or the index would silently list
# the default configs' cards instead of the ones it just rendered.
def generate_index(output_dir, config_filenames=None):
    scripts_dir = os.path.dirname(os.path.abspath(__file__))
    config_dir = os.path.join(scripts_dir, "..", "configs")

    cards = _collect_cards(config_dir, config_filenames or DEFAULT_CONFIG_FILENAMES)
    html = _render_html(cards)

    with open(os.path.join(output_dir, "index.html"), "w") as f:
        f.write(html)
